import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const title = "Ineer Energy | NitroSolutions"
  const meta_title = "Parceria entre NitroSolutions e IneerEnergy"
  const description = ""
  const image = ""
  const noindex = ""
  const canonical = ""

  return (
    <html lang="pt-br">
      <body className={`${inter.className} md:overflow-hidden`} >{children}</body>
    </html>
  );
}
